name: kubernetes!!
on:
    push:
        branches: 
            - master
    workflow_dispatch:
jobs:
    build-deploy:
        runs-on: jokes-api
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}

            - name: Build image
              run: |
                cd ./api
                docker build -t rachelallen1/joke-api-web-student:${{github.run_number}} .

            - name: push the image to docker, with the latest run number
              run: docker push rachelallen1/joke-api-web-student:${{github.run_number}}

            #deploy to kubernetes here
            - name: kubernetes deployment
              run: |
                export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin
                
                export IMAGE_TAG=${{github.run_number}}
                for file in kube/*; do
                    cat "$file" | envsubst | kubectl apply -f -;
                done

            - name: config map (do I need to put this before I push the image to docker so it runs the build ok?)
              run: |
                kubectl -n rdirectory delete configmap racheljokedatabase || true
                ls
                kubectl -n rdirectory create configmap racheljokedatabase --from-file=./database/init.sql
                