version: '1'
services:
  jokeDB:
    container_name: joke-db
    image: postgres:latest
    environment:
      POSTGRES_USER: joke-db
      POSTGRES_PASSWORD: joke-db
      POSTGRES_DB: joke-db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5440:5432"